# SSH keys via keychain — starts one ssh-agent and reuses it across shells,
# prompting for passphrases only on the first shell after boot. Every private
# key in ~/.ssh is detected by its "PRIVATE KEY" header, so this works no
# matter how the keys are named on a given machine. Must run before the
# Powerlevel10k instant prompt below, which swallows the console input
# keychain needs for passphrase prompts.
ssh_keys=()
for key in "$HOME"/.ssh/*(N); do
  [ -f "$key" ] || continue
  IFS= read -r header < "$key" || continue
  case "$header" in
    *"PRIVATE KEY"*) ssh_keys+=("$key") ;;
  esac
done
eval "$(keychain --eval --quiet --agents ssh "${ssh_keys[@]}")"
unset ssh_keys key header

# Enable Powerlevel10k instant prompt. Must stay near the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# History — flush after every command so entries survive non-graceful exits
# (e.g. zsh inside a detached tmux session being killed at reboot).
HISTFILE="$HOME/.zsh_history"
HISTSIZE=100000
SAVEHIST=200000
setopt APPEND_HISTORY INC_APPEND_HISTORY SHARE_HISTORY
setopt HIST_IGNORE_DUPS HIST_IGNORE_SPACE

# Completion
autoload -Uz compinit && compinit

export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"

alias ll='ls -alF'
alias cd=z
alias ..="cd .."
alias spy="source .venv/bin/activate"
alias ppy='export PYTHONPATH=$PWD:$PYTHONPATH'
alias copy="xclip -sel clip"

# Compatibility for logging into a remote terminal
alias ssh="TERM=xterm-256color ssh"

eval "$(zoxide init zsh)"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export TERM=xterm-256color
export DOCKER_HOST=unix://$HOME/.docker/desktop/docker.sock

# Powerlevel10k theme (cloned by install.sh)
P10K_THEME="$HOME/.dotfiles/zsh/powerlevel10k/powerlevel10k.zsh-theme"
[ -f "$P10K_THEME" ] && source "$P10K_THEME"

# Generated by `p10k configure`. Run it once per machine to customize the prompt.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
